# ============================================================
# Random Forest Regression Model: Predicting HPD Extension Potential
# Input: hpd_training_data.csv (generated by previous script)
# Output:
#   - Model evaluation metrics (R², RMSE)
#   - Feature importance plot (PDF)
#   - Predicted vs actual scatter plot (PDF)
#   - Model object (saved as .rds file)
# ============================================================

# Install required packages if not already installed
if (!require("tidyverse")) install.packages("tidyverse")
if (!require("ranger")) install.packages("ranger")
if (!require("caret")) install.packages("caret")
if (!require("ggplot2")) install.packages("ggplot2")

library(tidyverse)
library(ranger)
library(caret)
library(ggplot2)

# ============================================================
# 1. Load data
# ============================================================

data_file <- "hpd_training_data.csv"
if (!file.exists(data_file)) stop("File not found: ", data_file)

df <- read.csv(data_file, stringsAsFactors = FALSE)
cat("Data loaded: ", nrow(df), " rows, ", ncol(df), " columns\n")

# ============================================================
# 2. Feature selection and target variable definition
# ============================================================

# Target variable
target <- "extension_potential"

# Columns to exclude (those that would cause data leakage)
exclude_cols <- c(
  "site_id", "reference_position", "presence_frequency", "gap_frequency",
  "window_presence_mean", "window_gap_mean", "reference_aa", "most_frequent_aa",
  "main_presence_frequency", "main_extension_potential",
  "alt_presence_frequency", "alt_extension_potential"
)

# Ensure target is not in exclude list
exclude_cols <- setdiff(exclude_cols, target)

# Select feature columns
feature_cols <- setdiff(names(df), c(target, exclude_cols))
cat("Number of features:", length(feature_cols), "\n")
cat("Feature names:", paste(feature_cols, collapse = ", "), "\n")

# Extract feature matrix and target vector
X <- df[, feature_cols, drop = FALSE]
y <- df[[target]]

# Check for missing values
cat("Missing value summary:\n")
print(colSums(is.na(X)))

# ============================================================
# 3. Handle missing values (median for numeric, mode for categorical)
# ============================================================

# Numeric columns
numeric_cols <- names(X)[sapply(X, is.numeric)]
for (col in numeric_cols) {
  if (any(is.na(X[[col]]))) {
    med_val <- median(X[[col]], na.rm = TRUE)
    X[[col]][is.na(X[[col]])] <- med_val
    cat("Imputed numeric column", col, "with median:", med_val, "\n")
  }
}

# Factor columns
factor_cols <- names(X)[sapply(X, is.character) | sapply(X, is.factor)]
for (col in factor_cols) {
  if (any(is.na(X[[col]]))) {
    mode_val <- names(sort(table(X[[col]], useNA = "no"), decreasing = TRUE))[1]
    X[[col]][is.na(X[[col]])] <- mode_val
    cat("Imputed factor column", col, "with mode:", mode_val, "\n")
  }
}

# Ensure factor columns are of type factor
X[factor_cols] <- lapply(X[factor_cols], as.factor)

# ============================================================
# 4. Split into training and test sets (80/20, fixed seed)
# ============================================================

set.seed(2026)

train_indices <- createDataPartition(y, p = 0.8, list = FALSE)
X_train <- X[train_indices, ]
y_train <- y[train_indices]
X_test  <- X[-train_indices, ]
y_test  <- y[-train_indices]

cat("Training set size:", length(y_train), "\n")
cat("Test set size:", length(y_test), "\n")

# ============================================================
# 5. Train Random Forest regression model (using ranger)
# ============================================================

train_data <- cbind(y_train, X_train)
colnames(train_data)[1] <- target

cat("\nTraining Random Forest model...\n")
rf_model <- ranger(
  formula = as.formula(paste(target, "~ .")),
  data = train_data,
  num.trees = 500,
  mtry = floor(sqrt(ncol(X_train))),
  min.node.size = 5,
  importance = "impurity",
  write.forest = TRUE,
  seed = 123
)
cat("Model training completed\n")

# ============================================================
# 6. Model evaluation
# ============================================================

train_pred <- predict(rf_model, data = train_data)$predictions
test_pred  <- predict(rf_model, data = X_test)$predictions

train_rmse <- RMSE(train_pred, y_train)
train_r2   <- R2(train_pred, y_train)
test_rmse  <- RMSE(test_pred, y_test)
test_r2    <- R2(test_pred, y_test)

cat("\n=== Model Evaluation ===\n")
cat("Training set RMSE:", round(train_rmse, 4), " R²:", round(train_r2, 4), "\n")
cat("Test set RMSE:", round(test_rmse, 4), " R²:", round(test_r2, 4), "\n")

# ============================================================
# 7. Feature importance
# ============================================================

importance_df <- data.frame(
  Feature = names(rf_model$variable.importance),
  Importance = rf_model$variable.importance
) %>% arrange(desc(Importance))

cat("\nFeature importance ranking:\n")
print(head(importance_df, 10))

# English labels for feature importance plot
p_importance <- ggplot(importance_df, aes(x = reorder(Feature, Importance), y = Importance)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  coord_flip() +
  labs(title = "Feature Importance (based on impurity)",
       x = "Feature", y = "Importance Score") +
  theme_minimal(base_size = 12)

ggsave("feature_importance.pdf", plot = p_importance, width = 8, height = 6)
cat("Feature importance plot saved: feature_importance.pdf\n")

# ============================================================
# 8. Predicted vs actual scatter plot (test set)
# ============================================================

plot_data <- data.frame(
  Actual = y_test,
  Predicted = test_pred
)

# English labels for scatter plot
p_scatter <- ggplot(plot_data, aes(x = Actual, y = Predicted)) +
  geom_point(alpha = 0.5, color = "darkblue") +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "red", size = 1) +
  labs(title = "Test Set: Actual vs Predicted Extension Potential",
       x = "Actual Extension Potential",
       y = "Predicted Extension Potential") +
  annotate("text", x = 0.2, y = 0.8, 
           label = paste0("R² = ", round(test_r2, 3), "\nRMSE = ", round(test_rmse, 3))) +
  theme_minimal(base_size = 12)

ggsave("prediction_scatter.pdf", plot = p_scatter, width = 8, height = 6)
cat("Prediction scatter plot saved: prediction_scatter.pdf\n")

# ============================================================
# 9. Save model object (for later use)
# ============================================================

saveRDS(rf_model, file = "rf_model_extension.rds")
cat("Model object saved: rf_model_extension.rds\n")

feature_names <- colnames(X_train)
saveRDS(feature_names, file = "feature_names.rds")
cat("Feature names list saved: feature_names.rds\n")

cat("\n✅ All steps completed!\n")

